### ISSUE TITLE
migrate the project  to null safety

### ISSUE THREAD

**Issue by lucmichalski** [Bluewolf787/autospotify#18]
Hi @Bluewolf787 ,

Hope you are all well !

I am trying your great ptoject and I was wondering if you could migrate it to full null-safety ?

If look after a null-safe version of "data_connection_checker" package, please use this reference:
```yaml
  data_connection_checker:
    git:https://github.com/bobanalappat/data_connection_checker
```

Thanks for any insights or inputs on that :-)

Cheers,
Luc

**Comment by Bluewolf787** [comment]
Hello Luc,

Thank you for the feedback.
I can remember that I didn't upgraded it yet because of some packages weren't on null-safety.
But I'll take a look on that in the next few days.

Greetings,
Richard
